server:
  port: 8081

spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5432/users
    #username: root
    #password: 1234
    #driver-class-name: org.postgresql.Driver

  #jpa:
    #hibernate:
      #ddl-auto: update
    #show-sql: true

  #sql:
    #init:
      #mode: always              # Spring Boot 2.5+
      #continue-on-error: false
      #data-locations: classpath:data.sql
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

debug: false